-- =====================================================================
-- 20260708100001_perf_fk_indexes.sql
-- Cria índices de cobertura para 208 foreign keys sem índice
-- (advisor Supabase: unindexed_foreign_keys, 221 avisos).
-- NÃO APLICAR EM PRODUÇÃO ANTES DE VALIDAR EM HOMOLOGAÇÃO.
--
-- IMPORTANTE: usa CREATE INDEX CONCURRENTLY → NÃO pode rodar dentro de
-- transação. Rode este arquivo com autocommit (psql sem -1 / sem BEGIN),
-- ou via 'supabase db push'. Se algum CONCURRENTLY falhar no meio, o índice
-- fica INVALID: dropar (DROP INDEX) e recriar.
-- IF NOT EXISTS torna o script re-executável.
-- =====================================================================

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_apr_validadores_tecnicos_validador_id ON public.apr_validadores_tecnicos (validador_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cmp_categorias_alcada1_aprovador_id ON public.cmp_categorias (alcada1_aprovador_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cmp_categorias_alcada2_aprovador_id ON public.cmp_categorias (alcada2_aprovador_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cmp_categorias_validador_tecnico_id ON public.cmp_categorias (validador_tecnico_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cmp_cotacoes_concluido_por_id ON public.cmp_cotacoes (concluido_por_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cmp_pedido_impostos_registrado_por_id ON public.cmp_pedido_impostos (registrado_por_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cmp_requisicao_itens_atendido_em_pedido_id ON public.cmp_requisicao_itens (atendido_em_pedido_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cmp_requisicoes_base_destino_id ON public.cmp_requisicoes (base_destino_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cmp_requisicoes_origem_solicitacao_id ON public.cmp_requisicoes (origem_solicitacao_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_con_assinaturas_minuta_id ON public.con_assinaturas (minuta_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_con_config_analise_updated_by ON public.con_config_analise (updated_by);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_con_contratos_solicitacao_id ON public.con_contratos (solicitacao_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_con_equipe_pj_contrato_id ON public.con_equipe_pj (contrato_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_con_medicao_itens_contrato_item_id ON public.con_medicao_itens (contrato_item_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_con_minutas_created_by ON public.con_minutas (created_by);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_con_modelos_contrato_created_by ON public.con_modelos_contrato (created_by);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_con_reajustes_aplicado_por ON public.con_reajustes (aplicado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_con_resumos_executivos_created_by ON public.con_resumos_executivos (created_by);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_con_solicitacao_historico_executado_por ON public.con_solicitacao_historico (executado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_con_solicitacoes_created_by ON public.con_solicitacoes (created_by);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_con_solicitacoes_solicitante_id ON public.con_solicitacoes (solicitante_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ctrl_cenarios_criado_por ON public.ctrl_cenarios (criado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ctrl_indicadores_producao_obra_id ON public.ctrl_indicadores_producao (obra_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ctrl_orcamentos_aprovado_por ON public.ctrl_orcamentos (aprovado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_desp_adiantamentos_classe_financeira_id ON public.desp_adiantamentos (classe_financeira_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_desp_adiantamentos_aprovacao_id ON public.desp_adiantamentos (aprovacao_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_desp_adiantamentos_centro_custo_id ON public.desp_adiantamentos (centro_custo_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_est_bases_pmo_projeto_id ON public.est_bases (pmo_projeto_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_est_bases_centro_custo_id ON public.est_bases (centro_custo_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_est_cautela_favoritos_item_id ON public.est_cautela_favoritos (item_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_est_cautela_itens_item_id ON public.est_cautela_itens (item_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_est_cautelas_base_id ON public.est_cautelas (base_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_est_solicitacoes_obra_id ON public.est_solicitacoes (obra_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_est_solicitacoes_solicitante_id ON public.est_solicitacoes (solicitante_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_est_solicitacoes_base_destino_id ON public.est_solicitacoes (base_destino_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_est_solicitacoes_cmp_requisicao_id ON public.est_solicitacoes (cmp_requisicao_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fin_apontamentos_cartao_portador_id ON public.fin_apontamentos_cartao (portador_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fin_apontamentos_cartao_projeto_id ON public.fin_apontamentos_cartao (projeto_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fin_apontamentos_cartao_item_fatura_id ON public.fin_apontamentos_cartao (item_fatura_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fin_contas_pagar_cartao_id ON public.fin_contas_pagar (cartao_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fin_extratos_import_conta_id ON public.fin_extratos_import (conta_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fin_itens_fatura_cartao_apontamento_id ON public.fin_itens_fatura_cartao (apontamento_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fin_itens_fatura_cartao_cartao_id ON public.fin_itens_fatura_cartao (cartao_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fin_legado_custos_contrato_id ON public.fin_legado_custos (contrato_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fis_notas_fiscais_criado_por ON public.fis_notas_fiscais (criado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_abastecimentos_autorizado_por ON public.fro_abastecimentos (autorizado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_abastecimentos_motorista_id ON public.fro_abastecimentos (motorista_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_alocacoes_obra_id ON public.fro_alocacoes (obra_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_alocacoes_veiculo_id ON public.fro_alocacoes (veiculo_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_alocacoes_hist_obra_destino ON public.fro_alocacoes_hist (obra_destino);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_alocacoes_hist_feito_por ON public.fro_alocacoes_hist (feito_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_alocacoes_hist_obra_origem ON public.fro_alocacoes_hist (obra_origem);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_avaliacoes_fornecedor_avaliador_id ON public.fro_avaliacoes_fornecedor (avaliador_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_checklist_execucao_itens_template_item_id ON public.fro_checklist_execucao_itens (template_item_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_checklist_execucao_itens_execucao_id ON public.fro_checklist_execucao_itens (execucao_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_checklist_execucoes_alocacao_id ON public.fro_checklist_execucoes (alocacao_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_checklist_execucoes_template_id ON public.fro_checklist_execucoes (template_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_checklist_execucoes_veiculo_id ON public.fro_checklist_execucoes (veiculo_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_checklist_fotos_execucao_id ON public.fro_checklist_fotos (execucao_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_checklist_fotos_item_id ON public.fro_checklist_fotos (item_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_checklist_template_itens_template_id ON public.fro_checklist_template_itens (template_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_checklists_motorista_id ON public.fro_checklists (motorista_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_multas_veiculo_id ON public.fro_multas (veiculo_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_ocorrencias_telemetria_analista_id ON public.fro_ocorrencias_telemetria (analista_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_ocorrencias_telemetria_motorista_id ON public.fro_ocorrencias_telemetria (motorista_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_ordens_servico_analista_id ON public.fro_ordens_servico (analista_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_ordens_servico_aprovado_por ON public.fro_ordens_servico (aprovado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_ordens_servico_rejeitado_por ON public.fro_ordens_servico (rejeitado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_veiculo_acessorios_acessorio_id ON public.fro_veiculo_acessorios (acessorio_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fro_veiculos_motorista_responsavel_id ON public.fro_veiculos (motorista_responsavel_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loc_acordos_imovel_id ON public.loc_acordos (imovel_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loc_aditivos_imovel_id ON public.loc_aditivos (imovel_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loc_entradas_centro_custo_id ON public.loc_entradas (centro_custo_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loc_entradas_imovel_id ON public.loc_entradas (imovel_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loc_faturas_imovel_id ON public.loc_faturas (imovel_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loc_imoveis_centro_custo_id ON public.loc_imoveis (centro_custo_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loc_imoveis_contrato_id ON public.loc_imoveis (contrato_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loc_imoveis_empresa_id ON public.loc_imoveis (empresa_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loc_saidas_imovel_id ON public.loc_saidas (imovel_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loc_solicitacoes_imovel_id ON public.loc_solicitacoes (imovel_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loc_vistoria_fotos_item_id ON public.loc_vistoria_fotos (item_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loc_vistoria_fotos_vistoria_id ON public.loc_vistoria_fotos (vistoria_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loc_vistoria_itens_vistoria_id ON public.loc_vistoria_itens (vistoria_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loc_vistorias_entrada_id ON public.loc_vistorias (entrada_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loc_vistorias_imovel_id ON public.loc_vistorias (imovel_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loc_vistorias_saida_id ON public.loc_vistorias (saida_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_log_avaliacoes_avaliado_por ON public.log_avaliacoes (avaliado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_log_checklists_expedicao_conferido_por ON public.log_checklists_expedicao (conferido_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_log_nfe_emitida_por ON public.log_nfe (emitida_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_log_ocorrencias_registrado_por ON public.log_ocorrencias (registrado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_log_recebimentos_base_id ON public.log_recebimentos (base_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_log_recebimentos_confirmado_por ON public.log_recebimentos (confirmado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_log_solicitacoes_aprovado_por ON public.log_solicitacoes (aprovado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_log_solicitacoes_solicitante_id ON public.log_solicitacoes (solicitante_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_log_solicitacoes_validado_por ON public.log_solicitacoes (validado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_log_transportes_despachado_por ON public.log_transportes (despachado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_log_viagens_aprovado_por ON public.log_viagens (aprovado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_log_viagens_criado_por ON public.log_viagens (criado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_log_viagens_transportadora_id ON public.log_viagens (transportadora_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_mural_banners_criado_por ON public.mural_banners (criado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_obr_adiantamentos_aprovado_por ON public.obr_adiantamentos (aprovado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_obr_adiantamentos_solicitante_id ON public.obr_adiantamentos (solicitante_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_obr_apontamentos_apontado_por ON public.obr_apontamentos (apontado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_obr_apontamentos_contrato_item_id ON public.obr_apontamentos (contrato_item_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_obr_apontamentos_frente_id ON public.obr_apontamentos (frente_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_obr_apontamentos_validado_por ON public.obr_apontamentos (validado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_obr_equipes_colaborador_id ON public.obr_equipes (colaborador_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_obr_equipes_frente_id ON public.obr_equipes (frente_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_obr_planejamento_equipe_created_by ON public.obr_planejamento_equipe (created_by);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_obr_prestacao_contas_aprovador_id ON public.obr_prestacao_contas (aprovador_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_obr_prestacao_contas_adiantamento_id ON public.obr_prestacao_contas (adiantamento_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_obr_prestacao_contas_centro_custo_id ON public.obr_prestacao_contas (centro_custo_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_obr_prestacao_contas_classe_financeira_id ON public.obr_prestacao_contas (classe_financeira_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_obr_prestacao_contas_solicitante_id ON public.obr_prestacao_contas (solicitante_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_obr_rdo_responsavel ON public.obr_rdo (responsavel);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pat_transferencias_base_origem_id ON public.pat_transferencias (base_origem_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pat_transferencias_base_destino_id ON public.pat_transferencias (base_destino_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_aceite_contrato_id ON public.pmo_aceite (contrato_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_avanco_fisico_projeto_id ON public.pmo_avanco_fisico (projeto_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_documentos_projeto_id ON public.pmo_documentos (projeto_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_eap_projeto_id ON public.pmo_eap (projeto_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_entregaveis_eap_id ON public.pmo_entregaveis (eap_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_entregaveis_projeto_id ON public.pmo_entregaveis (projeto_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_histograma_projeto_id ON public.pmo_histograma (projeto_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_indicadores_snapshot_projeto_id ON public.pmo_indicadores_snapshot (projeto_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_medicao_itens_contrato_item_id ON public.pmo_medicao_itens (contrato_item_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_medicao_itens_projeto_id ON public.pmo_medicao_itens (projeto_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_medicao_resumo_projeto_id ON public.pmo_medicao_resumo (projeto_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_mudancas_solicitado_por ON public.pmo_mudancas (solicitado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_orcamento_projeto_id ON public.pmo_orcamento (projeto_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_plano_acao_projeto_id ON public.pmo_plano_acao (projeto_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_portfolio_contrato_id ON public.pmo_portfolio (contrato_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_projetos_contrato_id ON public.pmo_projetos (contrato_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_reunioes_portfolio_id ON public.pmo_reunioes (portfolio_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_riscos_projeto_id ON public.pmo_riscos (projeto_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_status_report_gerado_por ON public.pmo_status_report (gerado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_status_report_projeto_id ON public.pmo_status_report (projeto_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_tarefas_responsavel_id ON public.pmo_tarefas (responsavel_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_tarefas_eap_id ON public.pmo_tarefas (eap_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pmo_tarefas_projeto_id ON public.pmo_tarefas (projeto_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_qsma_condicionantes_licenca_id ON public.qsma_condicionantes (licenca_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_qsma_epi_entregas_epi_id ON public.qsma_epi_entregas (epi_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_qsma_epi_entregas_ficha_id ON public.qsma_epi_entregas (ficha_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_qsma_inspecoes_modelo_id ON public.qsma_inspecoes (modelo_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_qsma_inspecoes_tst_alocacao_id ON public.qsma_inspecoes (tst_alocacao_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_qsma_matriz_treinamento_treinamento_id ON public.qsma_matriz_treinamento (treinamento_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_qsma_ocorrencias_sgi_registro_id ON public.qsma_ocorrencias (sgi_registro_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_admissao_anexos_candidato_id ON public.rh_admissao_anexos (candidato_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_admissao_mobilizacao_alojamento_imovel_id ON public.rh_admissao_mobilizacao (alojamento_imovel_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_admissao_mobilizacao_apresentacao_base_id ON public.rh_admissao_mobilizacao (apresentacao_base_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_admissao_mobilizacao_recebido_por_id ON public.rh_admissao_mobilizacao (recebido_por_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_admissao_treinamentos_candidato_id ON public.rh_admissao_treinamentos (candidato_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_admissoes_centro_custo_id ON public.rh_admissoes (centro_custo_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_admissoes_colaborador_id ON public.rh_admissoes (colaborador_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_admissoes_obra_prevista_id ON public.rh_admissoes (obra_prevista_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_admissoes_registrado_por ON public.rh_admissoes (registrado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_colaboradores_gestor_id ON public.rh_colaboradores (gestor_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_colaboradores_perfil_id ON public.rh_colaboradores (perfil_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_comunicados_criado_por ON public.rh_comunicados (criado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_dependentes_colaborador_id ON public.rh_dependentes (colaborador_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_desligamentos_colaborador_id ON public.rh_desligamentos (colaborador_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_desligamentos_registrado_por ON public.rh_desligamentos (registrado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_documentos_colaborador_id ON public.rh_documentos (colaborador_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_holerites_uploaded_by ON public.rh_holerites (uploaded_by);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_movimentacoes_registrado_por ON public.rh_movimentacoes (registrado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_movimentacoes_colaborador_id ON public.rh_movimentacoes (colaborador_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_movimentacoes_obra_anterior_id ON public.rh_movimentacoes (obra_anterior_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_movimentacoes_obra_nova_id ON public.rh_movimentacoes (obra_nova_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_ponto_aprovacao_base_id ON public.rh_ponto_aprovacao (base_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_ponto_dia_obra_id ON public.rh_ponto_dia (obra_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_ponto_linkdisp_base_id ON public.rh_ponto_linkdisp (base_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_ponto_saldo_mes_colaborador_id ON public.rh_ponto_saldo_mes (colaborador_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rh_verificacoes_colaborador_id ON public.rh_verificacoes (colaborador_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sgi_acoes_responsavel_id ON public.sgi_acoes (responsavel_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sgi_analise_causa_analisado_por_id ON public.sgi_analise_causa (analisado_por_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sgi_analise_causa_registro_id ON public.sgi_analise_causa (registro_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sgi_documento_aprovacoes_responsavel_id ON public.sgi_documento_aprovacoes (responsavel_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sgi_documento_versoes_alterado_por_id ON public.sgi_documento_versoes (alterado_por_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sgi_documentos_centro_custo_id ON public.sgi_documentos (centro_custo_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sgi_documentos_obra_id ON public.sgi_documentos (obra_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sgi_documentos_responsavel_id ON public.sgi_documentos (responsavel_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sgi_metas_checkin_registrado_por_id ON public.sgi_metas_checkin (registrado_por_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sgi_objetivos_responsavel_id ON public.sgi_objetivos (responsavel_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sgi_registros_obra_id ON public.sgi_registros (obra_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sgi_registros_responsavel_id ON public.sgi_registros (responsavel_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sgi_verificacao_registro_id ON public.sgi_verificacao (registro_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sgi_verificacao_verificado_por_id ON public.sgi_verificacao (verificado_por_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sig_prova_identidade_colaborador_id ON public.sig_prova_identidade (colaborador_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sig_prova_identidade_documento_id ON public.sig_prova_identidade (documento_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sys_obras_base_id ON public.sys_obras (base_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sys_obras_pmo_projeto_id ON public.sys_obras (pmo_projeto_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sys_perfis_base_id ON public.sys_perfis (base_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sys_pre_cadastros_revisado_por ON public.sys_pre_cadastros (revisado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sys_pre_cadastros_solicitado_por ON public.sys_pre_cadastros (solicitado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_tel_sync_state_veiculo_id ON public.tel_sync_state (veiculo_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ti_artigos_autor_id ON public.ti_artigos (autor_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ti_atendentes_adicionado_por ON public.ti_atendentes (adicionado_por);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ti_auditoria_lgpd_alvo_perfil_id ON public.ti_auditoria_lgpd (alvo_perfil_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ti_auditoria_lgpd_ator_id ON public.ti_auditoria_lgpd (ator_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ti_chamado_anexos_autor_id ON public.ti_chamado_anexos (autor_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ti_chamado_anexos_comentario_id ON public.ti_chamado_anexos (comentario_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ti_chamado_atividades_ator_id ON public.ti_chamado_atividades (ator_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ti_chamado_comentarios_autor_id ON public.ti_chamado_comentarios (autor_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ti_chamados_ativo_id ON public.ti_chamados (ativo_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ti_chamados_categoria_id ON public.ti_chamados (categoria_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ti_chamados_setor_id ON public.ti_chamados (setor_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ti_notificacoes_chamado_id ON public.ti_notificacoes (chamado_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ti_termos_entrega_criado_por_id ON public.ti_termos_entrega (criado_por_id);

-- =====================================================================
-- ROLLBACK (executar manualmente; também CONCURRENTLY, fora de transação):
-- =====================================================================
/*
DROP INDEX CONCURRENTLY IF EXISTS public.idx_apr_validadores_tecnicos_validador_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_cmp_categorias_alcada1_aprovador_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_cmp_categorias_alcada2_aprovador_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_cmp_categorias_validador_tecnico_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_cmp_cotacoes_concluido_por_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_cmp_pedido_impostos_registrado_por_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_cmp_requisicao_itens_atendido_em_pedido_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_cmp_requisicoes_base_destino_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_cmp_requisicoes_origem_solicitacao_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_con_assinaturas_minuta_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_con_config_analise_updated_by;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_con_contratos_solicitacao_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_con_equipe_pj_contrato_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_con_medicao_itens_contrato_item_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_con_minutas_created_by;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_con_modelos_contrato_created_by;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_con_reajustes_aplicado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_con_resumos_executivos_created_by;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_con_solicitacao_historico_executado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_con_solicitacoes_created_by;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_con_solicitacoes_solicitante_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_ctrl_cenarios_criado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_ctrl_indicadores_producao_obra_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_ctrl_orcamentos_aprovado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_desp_adiantamentos_classe_financeira_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_desp_adiantamentos_aprovacao_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_desp_adiantamentos_centro_custo_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_est_bases_pmo_projeto_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_est_bases_centro_custo_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_est_cautela_favoritos_item_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_est_cautela_itens_item_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_est_cautelas_base_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_est_solicitacoes_obra_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_est_solicitacoes_solicitante_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_est_solicitacoes_base_destino_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_est_solicitacoes_cmp_requisicao_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fin_apontamentos_cartao_portador_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fin_apontamentos_cartao_projeto_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fin_apontamentos_cartao_item_fatura_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fin_contas_pagar_cartao_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fin_extratos_import_conta_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fin_itens_fatura_cartao_apontamento_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fin_itens_fatura_cartao_cartao_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fin_legado_custos_contrato_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fis_notas_fiscais_criado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_abastecimentos_autorizado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_abastecimentos_motorista_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_alocacoes_obra_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_alocacoes_veiculo_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_alocacoes_hist_obra_destino;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_alocacoes_hist_feito_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_alocacoes_hist_obra_origem;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_avaliacoes_fornecedor_avaliador_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_checklist_execucao_itens_template_item_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_checklist_execucao_itens_execucao_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_checklist_execucoes_alocacao_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_checklist_execucoes_template_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_checklist_execucoes_veiculo_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_checklist_fotos_execucao_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_checklist_fotos_item_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_checklist_template_itens_template_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_checklists_motorista_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_multas_veiculo_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_ocorrencias_telemetria_analista_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_ocorrencias_telemetria_motorista_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_ordens_servico_analista_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_ordens_servico_aprovado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_ordens_servico_rejeitado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_veiculo_acessorios_acessorio_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_fro_veiculos_motorista_responsavel_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_loc_acordos_imovel_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_loc_aditivos_imovel_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_loc_entradas_centro_custo_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_loc_entradas_imovel_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_loc_faturas_imovel_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_loc_imoveis_centro_custo_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_loc_imoveis_contrato_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_loc_imoveis_empresa_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_loc_saidas_imovel_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_loc_solicitacoes_imovel_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_loc_vistoria_fotos_item_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_loc_vistoria_fotos_vistoria_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_loc_vistoria_itens_vistoria_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_loc_vistorias_entrada_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_loc_vistorias_imovel_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_loc_vistorias_saida_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_log_avaliacoes_avaliado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_log_checklists_expedicao_conferido_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_log_nfe_emitida_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_log_ocorrencias_registrado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_log_recebimentos_base_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_log_recebimentos_confirmado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_log_solicitacoes_aprovado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_log_solicitacoes_solicitante_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_log_solicitacoes_validado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_log_transportes_despachado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_log_viagens_aprovado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_log_viagens_criado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_log_viagens_transportadora_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_mural_banners_criado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_obr_adiantamentos_aprovado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_obr_adiantamentos_solicitante_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_obr_apontamentos_apontado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_obr_apontamentos_contrato_item_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_obr_apontamentos_frente_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_obr_apontamentos_validado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_obr_equipes_colaborador_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_obr_equipes_frente_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_obr_planejamento_equipe_created_by;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_obr_prestacao_contas_aprovador_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_obr_prestacao_contas_adiantamento_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_obr_prestacao_contas_centro_custo_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_obr_prestacao_contas_classe_financeira_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_obr_prestacao_contas_solicitante_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_obr_rdo_responsavel;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pat_transferencias_base_origem_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pat_transferencias_base_destino_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_aceite_contrato_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_avanco_fisico_projeto_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_documentos_projeto_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_eap_projeto_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_entregaveis_eap_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_entregaveis_projeto_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_histograma_projeto_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_indicadores_snapshot_projeto_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_medicao_itens_contrato_item_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_medicao_itens_projeto_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_medicao_resumo_projeto_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_mudancas_solicitado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_orcamento_projeto_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_plano_acao_projeto_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_portfolio_contrato_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_projetos_contrato_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_reunioes_portfolio_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_riscos_projeto_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_status_report_gerado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_status_report_projeto_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_tarefas_responsavel_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_tarefas_eap_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_pmo_tarefas_projeto_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_qsma_condicionantes_licenca_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_qsma_epi_entregas_epi_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_qsma_epi_entregas_ficha_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_qsma_inspecoes_modelo_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_qsma_inspecoes_tst_alocacao_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_qsma_matriz_treinamento_treinamento_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_qsma_ocorrencias_sgi_registro_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_admissao_anexos_candidato_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_admissao_mobilizacao_alojamento_imovel_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_admissao_mobilizacao_apresentacao_base_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_admissao_mobilizacao_recebido_por_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_admissao_treinamentos_candidato_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_admissoes_centro_custo_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_admissoes_colaborador_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_admissoes_obra_prevista_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_admissoes_registrado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_colaboradores_gestor_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_colaboradores_perfil_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_comunicados_criado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_dependentes_colaborador_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_desligamentos_colaborador_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_desligamentos_registrado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_documentos_colaborador_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_holerites_uploaded_by;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_movimentacoes_registrado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_movimentacoes_colaborador_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_movimentacoes_obra_anterior_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_movimentacoes_obra_nova_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_ponto_aprovacao_base_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_ponto_dia_obra_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_ponto_linkdisp_base_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_ponto_saldo_mes_colaborador_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_rh_verificacoes_colaborador_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sgi_acoes_responsavel_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sgi_analise_causa_analisado_por_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sgi_analise_causa_registro_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sgi_documento_aprovacoes_responsavel_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sgi_documento_versoes_alterado_por_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sgi_documentos_centro_custo_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sgi_documentos_obra_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sgi_documentos_responsavel_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sgi_metas_checkin_registrado_por_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sgi_objetivos_responsavel_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sgi_registros_obra_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sgi_registros_responsavel_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sgi_verificacao_registro_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sgi_verificacao_verificado_por_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sig_prova_identidade_colaborador_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sig_prova_identidade_documento_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sys_obras_base_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sys_obras_pmo_projeto_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sys_perfis_base_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sys_pre_cadastros_revisado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_sys_pre_cadastros_solicitado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_tel_sync_state_veiculo_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_ti_artigos_autor_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_ti_atendentes_adicionado_por;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_ti_auditoria_lgpd_alvo_perfil_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_ti_auditoria_lgpd_ator_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_ti_chamado_anexos_autor_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_ti_chamado_anexos_comentario_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_ti_chamado_atividades_ator_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_ti_chamado_comentarios_autor_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_ti_chamados_ativo_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_ti_chamados_categoria_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_ti_chamados_setor_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_ti_notificacoes_chamado_id;
DROP INDEX CONCURRENTLY IF EXISTS public.idx_ti_termos_entrega_criado_por_id;
*/
